### ISSUE TITLE
How to migrate from one network to another?

### ISSUE THREAD

**Issue by iliyaZelenko** [troolee/gridstack.js#257] opened 2015-10-17 19:23 UTC
Hi.
When reading the questions on the topic, he saw one primerchik, but there is nicely done: does not show where to move an item, move it wherever he wants.
Thank you.

**Comment by iliyaZelenko** [comment] 2015-10-19 15:54
http://www.codeproject.com/KB/WinRT/536519/GridView_DragDrop2.png

**Comment by troolee** [comment] 2016-02-18 03:16
Duplicate of #133

**Closed by troolee** 2016-02-18 03:16 UTC
