### ISSUE TITLE
Items overlapping eachother

### ISSUE THREAD

**Issue by tommielag** [troolee/gridstack.js#471] opened 2016-06-17 21:41 UTC
Hi!

I'm using Gridstack.js with custom content inside the div with the class .grid-stack-item-content which are dynamically cloned by the click of a button. However, trying to move these, sometimes a overlapping issue appears.

Please see this link:
https://gyazo.com/dc62b9e89cfec57b14ec8d4c6e5981e2

And my script for adding these "dynamic grid items":
```
jQuery(function($){
	var options = {
		disableResize: true,
        acceptWidgets: ".grid-stack-item"
	};
	$(".grid-stack").gridstack(options);


	$(".add-grid-green").click(function(e){
		var grid = $('#grid1').data('gridstack');
		var el = $(".oct2").clone();
		grid.addWidget(el, 0, 0, 3, 3, true);
		grid.movable(el, true);
		e.preventDefault();
	});
	$(".add-grid-blue").click(function(e){
		var grid = $('#grid1').data('gridstack');
		var el = $(".oct1").clone();
		grid.addWidget(el, 0, 0, 6, 6, true);
		grid.movable(el, true);
		e.preventDefault();
	});
});
```

Any ideas on why this appears?

Thank you,
Tommie

**Comment by radiolips** [comment] 2016-07-30 19:08
Thanks, Tommie! Could you provide a jsfiddle?

**Comment by radiolips** [comment] 2016-08-10 02:01
Closing. Reopen with more information if you're still having an issue.

**Closed by radiolips** 2016-08-10 02:01 UTC
Labels: status:need more info

**Comment by tracyalison11** [comment] 2016-08-22 13:28
@tommielag did you ever figure out what the issue is?
