### ISSUE TITLE
Drop widget into trash

### ISSUE THREAD

**Issue by Notheros** [troolee/gridstack.js#291] opened 2015-12-06 23:54 UTC
Is possible to implement a "drop to remove" feature? For example, drag and drop a widget inside a div (or any other element you want) to remove it.

I think this would be awesome!

**Comment by zspitzer** [comment] 2015-12-08 03:01
have a look at this to get you started 
http://stackoverflow.com/questions/9796934/jquery-ui-remove-element-when-dropped-into-a-div-using-droppable

**Comment by troolee** [comment] 2016-02-18 03:16
Duplicate of #133

**Closed by troolee** 2016-02-18 03:16 UTC
