### ISSUE TITLE
how to swap two grid items?

### ISSUE THREAD

**Issue by asonarya** [troolee/gridstack.js#181] opened 2015-07-08 19:42 UTC
swap the dragged and hovered positions.

**Comment by troolee** [comment] 2015-07-17 01:28
There is no suck possibility right now. But it is in TODO list...

**Comment by asonarya** [comment] 2015-07-19 14:04
Thanks! This is a great library you have

**Comment by alan12111** [comment] 2015-08-03 15:28
+1

**Comment by Onthrax** [comment] 2015-09-25 10:00
:+1:

**Comment by indriemarius** [comment] 2015-09-28 18:08
+1

**Comment by palpatine1991** [comment] 2015-10-22 15:59
+1

**Comment by edborden** [comment] 2015-10-31 21:09
+2

**Comment by iliyaZelenko** [comment] 2015-11-25 10:52
+

**Comment by gilhanan** [comment] 2015-11-25 15:26
+

**Comment by radiolips** [comment] 2016-02-18 16:31
Duplicate of #149 .

**Closed by radiolips** 2016-02-18 16:31 UTC
