### ISSUE TITLE
Move nested grids between mother grids

### ISSUE THREAD

**Issue by nnikolay** [troolee/gridstack.js#121] opened 2015-04-03 17:45 UTC
Hi, I have seen the feature of nested grids. If I create two mother grids and child (nested) grids in them, how can I move some nested grid in the other mother grid. Is this possible?

Thanks
Nik

**Comment by troolee** [comment] 2015-04-04 04:14
Do you mean widget from one second-level grid to another second-level grid?

**Comment by troolee** [comment] 2015-04-04 04:15
Please give a use case.

**Comment by abhi2abhi** [comment] 2015-04-04 06:30
Hi,
First of all I really appreciate your work. 
I have similar question. can we achieve below use case:
1> add new widget  
2> Using drag and drop make newly added widget a nested widget of any existing widget.

As of now, drag and drop is used for moving a widget on page.

**Comment by abhi2abhi** [comment] 2015-04-06 09:41
@troolee Any help ?

**Comment by jamessanderlin** [comment] 2015-05-12 21:55
@troolee I am trying to do something similar as well.

I am creating a form builder which uses gridstack for laying out the fields in the form. I am using nestable grids, so that I can make groupings of fields. This helps separate the different sections of the form and lets the user drag around the whole group at once. So you might have a contact form, with an "About You" field group, which contains a text field for "First Name" and a text field for "Last Name", and also an "Other Info" group which has a number field for "Age" and a text field for "Comments". I'd love for the user to be able to drag the "Age" field out of the "Other Info" group and into the "About You" group, but since those are two completely different grids (which are nested inside a parent grid, which is the whole Contact Form), I don't know how to do this. Is this possible?

**Comment by michaelj23** [comment] 2015-05-26 23:55
@troolee I would also love to see this implemented into the framework.

I am working on an application where users should be able to move modules flexibly within each other, regardless of nesting level. Is there a way that we can transfer items from one grid to another via drag and drop?
Any help is appreciated!

**Comment by abologna-r7** [comment] 2015-05-27 00:42
:+1:

**Comment by troolee** [comment] 2016-02-18 03:18
We're working on such possibility to move widgets between grids. I'm closing this issue because it's actually duplicate of #133

**Closed by troolee** 2016-02-18 03:18 UTC
