### ISSUE TITLE
Moving elements in a full grid

### ISSUE THREAD

**Issue by midito** [troolee/gridstack.js#239] opened 2015-10-03 14:23 UTC
Hi,
I want to make a grid limited in size (3x5), where users can move the elements.
I don't want to allow elements outside the grid, but if I limit it, when all spaces are occupied is not possible to move some elements because they collide.
DEMO: https://jsfiddle.net/tw6qvb7q/
It's possible to move the 3x1 elements up and down, but not the 1x1 elements horizontally.
Is there any way to fix this?

**Comment by midito** [comment] 2015-10-03 14:45
One solution i'm going to try is remove the height and width restrictions, but check if there are items outside of my desired area. I think gridstack does not include functions to check but, but it shouldn't be so complex to do. Any other ideas? 

PS. Thanks for doing this great library!

**Comment by HarryLonsdale** [comment] 2015-10-13 08:02
I also have such problems

**Comment by midito** [comment] 2015-10-13 12:17
I finally removed the height restriction and use only the width value. If you move something, the grid will have space to swap, but you have to check if everything is in your desired grid area before saving or using the grid. It would be nice if gridstack could support fixed sizes by swapping elements in the desired grid area.

**Comment by palpatine1991** [comment] 2015-10-22 15:52
Midito, is it possible to put your solution on fiddle?

Anyway I vote for adding this feature to Gridstack!

**Comment by midito** [comment] 2015-10-23 08:45
Hi,
Here you have the link: https://jsfiddle.net/tw6qvb7q/3/

It won't work on fiddle because the way we use it is to have a left column with some items (widgets). When you click on it, the widget will appear in the grid area, where you can move it and set its final position. The position of every item will be the next free one.

I have constrained only the width. Every time there is a change, we check if there are items outside the grid (is_area_empty()) and set a variable to false if the grid is has problems. Also, any element outside the grid area will be marked in red using css.

I've set the grid area with black background temporary for fiddle, but we use a grid image background in development. 

We have used "full width" widgets only, so if you need to add more than one item in the same row, you may have some problems. 

I hope it helps.

**Comment by radiolips** [comment] 2016-02-19 16:39
This would require an enhancement in the algorithm for collision detection and widget movement. In this example, moving up and down would still not be possible, aside from the large blocks, but swapping the smaller blocks would be. Several tickets are open for this and will be linked shortly.

**Comment by radiolips** [comment] 2016-02-22 20:12
Duplicate of #149. Closing this ticket in favor of that one. Please reopen if you feel that ticket will not satisfy what you're asking for here.

**Closed by radiolips** 2016-02-22 20:12 UTC
Labels: type:enhancement
