### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by h-nazzal** [troolee/gridstack.js#195] opened 2015-07-30 19:22 UTC
hi there ...
first off i love this project! but im afraid there is few things that need to be done in order to make this usable ... 

decrease dependency list  : 
A - most importantly the jquery-ui is just a bloat of code that IMHO can be replaced better/slimmer libraries out there.

currently the jquery-ui minified version is 55kb (using custom build with only the required modules).
while i believe we can go as low as 18.3 kb using interactjs which will also remove the touch devices additional dependency.

and even better we could use https://github.com/bevacqua/dragula .. which is only 10kb (minified) 

both of the above libraries will remove the jquery dependency which will help bring down the size of this plugin. (a small jquery hook can be added) 

b - lodash is no requirement for this project (and i cant figure out why it was used) : 
i believe all of the code can be replaced by in house jquery functions ($.each , $.filiter ) 

knowing that these are some big code base changes. i just would love to see what you think about these points ?

**Comment by troolee** [comment] 2015-07-31 00:17
Hi,

It's a good point. And I will try to reduce these dependencies in future releases. The main goals for now are to improve performance on big grids, drag-n-drop between grids.

**Comment by h-nazzal** [comment] 2015-07-31 10:19
@troolee  actually im working on the dependacies issue right now im really getting some good results so far.

but i'd love to participate in some performance tweaks ,could you please point me out to where i can find the issues that need to fixed (in regards to the performance) ? 
and if you do have some test case/file that would show the performance issues please share it ..

**Comment by troolee** [comment] 2015-08-01 17:29
You can check this sample http://troolee.github.io/gridstack.js/demo/knockout.html Performance dramatically drop when you add a lot of widgets. The problem is in fix_collision algorithm which is not optimized. First of all it's recursion...

**Comment by h-nazzal** [comment] 2015-08-02 10:21
yeah i debugged the code and already... i think im close to some thing in here ...

**Comment by h-nazzal** [comment] 2015-08-03 16:13
@troolee i figured out/ fixed the problem ... i will make a PR

**Comment by KevinSimple** [comment] 2015-10-12 09:16
@h-nazzal , mate, did you make any progress on the performance? I am optimizing as well.

**Comment by h-nazzal** [comment] 2015-11-08 16:25
@KevinSimple  sorry for the late response, tbh i gaveup on this project long ago . reason being, it doesn't have enough development cycles and the whole implementation is faulty ... 

the way that collision detection works is fine but shifting boxes around is just an infinite loop of doing the same thing (move one box,  re-detect collision, repeat ) all over again which turns out to be processor intensive ...

**Comment by mazing** [comment] 2016-02-15 23:56
+1 for using dragula instead of jquery ui!

**Comment by radiolips** [comment] 2016-02-18 14:31
Dragula does not handle resize. We could use dragula, but we would need to write new custom code for resizing - or continue to use jquery-ui.

**Comment by radiolips** [comment] 2016-02-20 14:07
To give an update - for version 1.0, gridstack will use an external "plugin" system to incorporate moving and resizing. It will most likely support jquery-ui, dragula (just for dragging), and interactjs from the get-go.

**Comment by radiolips** [comment] 2016-02-22 13:10
Closing this out. The enhancements have been logged and will be addressed, but this issue is a little out-of-hand.

**Closed by radiolips** 2016-02-22 13:10 UTC
