### ISSUE TITLE
removing an element by dragging does not trigger the 'removed' event

### ISSUE THREAD

**Issue by sthuck** [troolee/gridstack.js#550] opened 2016-11-03 14:43 UTC
Hi,

Not sure if this is a bug or intended behaviour, but dragging an element outside the grid to delete it using the 'removable: true' option, does not trigger 'removed' event. 
Relevant code seems to be [here](https://github.com/troolee/gridstack.js/blob/master/src/gridstack.js#L1156). 

If this is intended behaviour my two cents are that it should trigger an event :)

**Comment by radiolips** [comment] 2016-12-20 14:21
@sthuck You're right. This will be resolved.

**Comment by jorsai** [comment] 2017-01-09 19:00
Sorry I'm relative new at GitHub. 
How can we know if this bug is fixed?

**Comment by RodgerLai** [comment] 2017-03-30 08:50
@jorsai you will know the bug fixed when the issue is closed

**Comment by radiolips** [comment] 2017-04-21 18:57
@jorsai Fixed in develop branch. It'll be released later this evening.

**Closed by radiolips** 2017-04-21 18:57 UTC
Labels: type:bug

**Comment by jordihuertas** [comment] 2017-06-18 15:24
Thank you!
