### ISSUE TITLE
events for add & removing widgets

### ISSUE THREAD

**Issue by xLink** [troolee/gridstack.js#106] opened 2015-03-27 23:17 UTC
any chance you could add events for when a widget gets added, and one for removal of a widget too

**Comment by troolee** [comment] 2015-03-27 23:25
Sure, I can do this.

**Comment by FredFaust** [comment] 2015-06-15 18:51
While playing with the code for add and remove, could you check [this issue](https://github.com/troolee/gridstack.js/issues/167).

Thanks !

**Comment by radiolips** [comment] 2016-02-20 17:19
Duplicate of #54. Emitting events for adding and removing widgets will be completed for v0.2.5 and the original ticket will be updated when the feature has been completed.

**Closed by radiolips** 2016-02-20 17:19 UTC
