### ISSUE TITLE
resizestop event issue

### ISSUE THREAD

**Issue by lopezcjf** [troolee/gridstack.js#142] opened 2015-05-08 18:34 UTC
Hi,

After resizing an element I need to catch the new width / height. For that purpose I'm using the resizestop event but I couldn't find the new values in here (only the old ones)

It seems to be that the values are updated somewhere after this event , and I only can get the new values on the next resize event (which of course is not suitable)

Thanks

**Comment by troolee** [comment] 2015-05-15 16:20
Why don't you use `onchange` event? An `onchange` handler receives all affected items.

**Comment by m5n** [comment] 2015-05-15 19:21
This seems to have changed between 0.2.2 and the current 0.2.3-dev. Formerly, the new values were accessible, now the old values are returned.

Using onchange is cumbersome as it contains details about all items that changed because of a resize, rather than just the one of interest.

**Comment by lopezcjf** [comment] 2015-05-15 19:49
I guess I agree with m5c in this. It is good to support each event type with it's relevant data, specially for complex scenarios.

**Comment by m5n** [comment] 2015-05-15 20:41
I played with 0.2.3-dev a bit more, and I was wrong, the new values do get sent. (I have some other code that has a different outcome from 0.2.2, still investigating that.)

The "ui" object contains the originalSize and size properties that give you what you need:

    $('.grid-stack').on('resizestop', function (event, ui) { ... }

**Comment by lopezcjf** [comment] 2015-05-15 20:47
I swear I examined both objects and found the old values in both. But mistakes can happen! I will re-check that tonight ;)

**Comment by troolee** [comment] 2015-05-15 20:49
It could probably be because of animation. Please check it with and without.

**Comment by mkez00** [comment] 2015-07-17 15:17
I can confirm what lopezcjf is saying.

```javascript
$('.grid-stack').on('resizestop', function (event, ui) {
console.debug(ui.element[0].attributes.getNamedItem("data-gs-width"));
console.debug(ui.element[0].attributes.getNamedItem("data-gs-width").value);
});
```

first console output is: data-gs-width="1"
second console output is: 12

First console output is the actual new width of widget and second is the old value.  I am not using animation.

**Comment by derekm** [comment] 2015-08-07 21:24
See also issue #133, where there is a fix for this posted.

**Comment by radiolips** [comment] 2016-02-20 01:52
Closing, as @derekm's code has been merged. @lopezcjf please reopen if you're having a problem still.

**Closed by radiolips** 2016-02-20 01:52 UTC
Labels: type:bug
