### ISSUE TITLE
Setting the vertical margin attribute to a high value causes the grid items to stretch

### ISSUE THREAD

**Issue by davidpoling** [troolee/gridstack.js#599] opened 2017-02-06 16:58 UTC
On my application, I have a configurable verticalMargin object that allows me to set that object at any point and update the verticalMargin attribute of gridstack. I noticed that if I set the verticalMargin to something like 400px, it stretches all of the grid items vertically, in what seems like its adjusting the height.

I originally thought this was something on my end that I was doing wrong, however I got curious and tested it on the gridstack demo. Provided is a screenshot of the issue on the gridstack demo page.

![gridstack-vertical-margin](https://cloud.githubusercontent.com/assets/7083657/22657173/8af59c6e-ec63-11e6-929b-58bbe69f935f.png)

Here is a jsfiddle showing the widgets resizing https://jsfiddle.net/fhr7rh2j/2/

**Comment by radiolips** [comment] 2017-04-19 17:47
@davidpoling Thanks for reporting this! This isn't the first time that `verticalMargin` has caused us some issue. I believe I've identified the problem and will let you know when it's been resolved.

**Comment by radiolips** [comment] 2017-04-20 14:20
@davidpoling I took a deep dive into both the code and some fun theoretical situations. The tl;dr: this is not a bug at all.

Check this - all dashboard demos have very small vertical margins. I can explain why! _Vertical margins are impossible to pull off_. You may not believe what I'm about to say, but take out a sheet of paper, draw some rectangles, and you'll see what I mean:

For each increment of your widget's `height`, which, in pixels, you may expect to be calculated as `height * cellHeight`, it's actually going to look more like `height * cellHeight + verticalMargin * height`. `verticalMargin` needs to be considered because the grid will not otherwise line up. If you have two 1x1 squares at 1,1 and 1,2, and a 1x2 rectangle at 2,1, the bottom of all of these should line up exactly. Without adding `verticalMargin` to the height for each increment of the height, the bottoms won't line up. I'm closing this ticket, but please let me know if I can offer any more assistance here.

**Closed by radiolips** 2017-04-20 14:20 UTC
